/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sisÃ¤llÃ¶t. Sulkeaksesi tÃ¤mÃ¤n dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin tyÃ¶kalupalkki",legend:"Paina ${toolbarFocus} siirtyÃ¤ksesi tyÃ¶kalupalkkiin. Siirry seuraavaan ja edelliseen tyÃ¶kalupalkin ryhmÃ¤Ã¤n TAB ja SHIFT+TAB nÃ¤ppÃ¤imillÃ¤. Siirry seuraavaan ja edelliseen tyÃ¶kalupainikkeeseen kÃ¤yttÃ¤mÃ¤llÃ¤ NUOLI OIKEALLE tai NUOLI VASEMMALLE nÃ¤ppÃ¤imillÃ¤. Paina VÃ„LILYÃ–NTI tai ENTER nÃ¤ppÃ¤intÃ¤ aktivoidaksesi tyÃ¶kalupainikkeen."},
{name:"Editorin dialogi",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editorin oheisvalikko",legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS nÃ¤ppÃ¤imillÃ¤. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YLÃ–S nÃ¤ppÃ¤imillÃ¤. Paina VÃ„LILYÃ–NTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina VÃ„LILYÃ–NTI tai ENTER tai NUOLI OIKEALLE painiketta. SiirtyÃ¤ksesi takaisin valikon ylemmÃ¤lle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},
{name:"Editorin listalaatikko",legend:"Listalaatikon sisÃ¤llÃ¤ siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YLÃ–S painikkeilla. Paina VÃ„LILYÃ–NTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirtyÃ¤ksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina VÃ„LILYÃ–NTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"PienennÃ¤ tyÃ¶kalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryÃ¤ksesi lÃ¤himpÃ¤Ã¤n kursorin edellÃ¤ olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkÃ¤istÃ¤ HR elementtiÃ¤. Toista nÃ¤ppÃ¤inyhdistelmÃ¤Ã¤ pÃ¤Ã¤stÃ¤ksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryÃ¤ksesi lÃ¤himpÃ¤Ã¤n kursorin jÃ¤lkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkÃ¤istÃ¤ HR elementtiÃ¤. Toista nÃ¤ppÃ¤inyhdistelmÃ¤Ã¤ pÃ¤Ã¤stÃ¤ksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"NumeronÃ¤ppÃ¤imistÃ¶ 0",numpad1:"NumeronÃ¤ppÃ¤imistÃ¶ 1",numpad2:"NumeronÃ¤ppÃ¤imistÃ¶ 2",numpad3:"NumeronÃ¤ppÃ¤imistÃ¶ 3",numpad4:"NumeronÃ¤ppÃ¤imistÃ¶ 4",numpad5:"NumeronÃ¤ppÃ¤imistÃ¶ 5",numpad6:"NumeronÃ¤ppÃ¤imistÃ¶ 6",numpad7:"NumeronÃ¤ppÃ¤imistÃ¶ 7",numpad8:"NumeronÃ¤ppÃ¤imistÃ¶ 8",
numpad9:"NumeronÃ¤ppÃ¤imistÃ¶ 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Puolipiste",equalSign:"Equal Sign",comma:"Pilkku",dash:"Dash",period:"Piste",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});
