/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilitÃ©",contents:"Contenu de l'aide. Pour fermer cette fenÃªtre, appuyez sur la touche Ã‰chap.",legend:[{name:"GÃ©nÃ©ral",items:[{name:"Barre d'outils de l'Ã©diteur",legend:"Appuyer sur ${toolbarFocus} pour accÃ©der Ã  la barre d'outils. Se dÃ©placer vers les groupes suivant ou prÃ©cÃ©dent de la barre d'outil avec les touches MAJ et MAJ+TAB. Se dÃ©placer vers les boutons suivant ou prÃ©cÃ©dent de la barre d'outils avec les touches FLÃˆCHE DROITE et FLÃˆCHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRÃ‰E pour activer le bouton de barre d'outils."},
{name:"FenÃªtre de l'Ã©diteur",legend:"Dans une boÃ®te de dialogue, appuyer sur Tab pour passer Ã  l'Ã©lÃ©ment suivant, appuyer sur Maj+Tab pour passer Ã  l'Ã©lÃ©ment prÃ©cÃ©dent, appuyer sur EntrÃ©e pour valider, appuyer sur Ã‰chap pour annuler. Quand une boÃ®te de dialogue possÃ¨de des onglets, la liste peut Ãªtre atteinte avec Alt+F10 ou avec Tab. Dans la liste des onglets, se dÃ©placer vers le suivant et le prÃ©cÃ©dent avec les flÃ¨ches Droite et Gauche respectivement."},{name:"Menu contextuel de l'Ã©diteur",legend:"Appuyer sur ${contextMenu} ou sur la touche Menu pour ouvrir le menu contextuel. Se dÃ©placer ensuite vers l'option suivante du menu avec la touche Tab ou la flÃ¨che Bas. Se dÃ©placer vers l'option prÃ©cÃ©dente avec le raccourci Maj+Tab ou la flÃ¨che Haut. appuyer sur la Barre d'espace ou la touche EntrÃ©e pour sÃ©lectionner l'option du menu. Appuyer sur la Barre d'espace, la touche EntrÃ©e ou la flÃ¨che Droite pour ouvrir le sous-menu de l'option sÃ©lectionnÃ©e. Revenir Ã  l'Ã©lÃ©ment de menu parent avec la touche Ã‰chap ou la flÃ¨che Gauche. Fermer le menu contextuel avec Ã‰chap."},
{name:"Zone de liste de l'Ã©diteur",legend:"Dans la liste en menu dÃ©roulant, se dÃ©placer vers l'Ã©lÃ©ment suivant de la liste avec la touche Tab ou la flÃ¨che Bas. Se dÃ©placer vers l'Ã©lÃ©ment prÃ©cÃ©dent de la liste avec le raccourci Maj+Tab ou la flÃ¨che Haut. Appuyer sur la Barre d'espace ou sur EntrÃ©e pour sÃ©lectionner l'option dans la liste. Appuyer sur Ã‰chap pour fermer le menu dÃ©roulant."},{name:"Barre du chemin d'Ã©lÃ©ments de l'Ã©diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre du fil d'Ariane des Ã©lÃ©ments. Se dÃ©placer vers le bouton d'Ã©lÃ©ment suivant avec la touche Tab ou la flÃ¨che Droite. Se dÃ©placer vers le bouton d'Ã©lÃ©ment prÃ©cÃ©dent avec le raccourci Maj+Tab ou la flÃ¨che Gauche. Appuyer sur la Barre d'espace ou sur EntrÃ©e pour sÃ©lectionner l'Ã©lÃ©ment dans l'Ã©diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Commande restaurer",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulignÃ©",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Commande d'accÃ¨s Ã  l'Ã©lÃ©ment sÃ©lectionnable prÃ©cÃ©dent",
legend:"Appuyer sur ${accessNextSpace} pour accÃ©der Ã  l'Ã©lÃ©ment sÃ©lectionnable inatteignable le plus proche avant le curseur, par exempleÂ : deux lignes horizontales adjacentes. RÃ©pÃ©ter la combinaison de touches pour atteindre les Ã©lÃ©ments sÃ©lectionnables prÃ©cÃ©dents."},{name:"Commande d'accÃ¨s Ã  l'Ã©lÃ©ment sÃ©lectionnable suivant",legend:"Appuyer sur ${accessNextSpace} pour accÃ©der Ã  l'Ã©lÃ©ment sÃ©lectionnable inatteignable le plus proche aprÃ¨s le curseur, par exempleÂ : deux lignes horizontales adjacentes. RÃ©pÃ©ter la combinaison de touches pour atteindre les Ã©lÃ©ments sÃ©lectionnables suivants."},
{name:" Aide sur l'accessibilitÃ©",legend:"Appuyer sur ${a11yHelp}"}]}],backspace:"Retour arriÃ¨re",tab:"Tabulation",enter:"EntrÃ©e",shift:"Majuscule",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Verr. Maj.",escape:"Ã‰chap",pageUp:"Page supÃ©rieure",pageDown:"Page suivante",end:"Fin",home:"Origine",leftArrow:"FlÃ¨che gauche",upArrow:"FlÃ¨che haut",rightArrow:"FlÃ¨che droite",downArrow:"FlÃ¨che basse",insert:"Inser","delete":"Supprimer",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",
selectKey:"Touche SÃ©lectionner",numpad0:"0 du pavÃ© numÃ©rique",numpad1:"1 du pavÃ© numÃ©rique",numpad2:"2 du pavÃ© numÃ©rique",numpad3:"3 du pavÃ© numÃ©rique",numpad4:"4 du pavÃ© numÃ©rique",numpad5:"5 du pavÃ© numÃ©rique",numpad6:"6 du pavÃ© numÃ©rique",numpad7:"7 du pavÃ© numÃ©rique",numpad8:"PavÃ© numÃ©rique 8",numpad9:"9 du pavÃ© numÃ©rique",multiply:"Multiplier",add:"Plus",subtract:"Moins",decimalPoint:"Point dÃ©cimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",
f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"ArrÃªt dÃ©fil.",semiColon:"Point-virgule",equalSign:"Signe Ã©gal",comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"ParenthÃ¨se ouvrante",backSlash:"Barre oblique inverse",closeBracket:"ParenthÃ¨se fermante",singleQuote:"Apostrophe"});
