/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"InstruciÃ³ns de accesibilidade",contents:"Axuda. Para pechar este diÃ¡logo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIÃšS+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o botÃ³n da barra de ferramentas."},
{name:"Editor de diÃ¡logo",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor do menÃº contextual",legend:"Prema ${contextMenu} ou a TECLA MENÃš para abrir o menÃº contextual. A seguir mÃ³vase Ã¡ seguinte opciÃ³n do menÃº con TAB ou FRECHA ABAIXO. MÃ³vase Ã¡ opciÃ³n anterior con MAIÃšS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opciÃ³n do menÃº. Abra o submenÃº da opciÃ³n actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do menÃº con ESC ou FRECHA ESQUERDA. Peche o menÃº contextual con ESC."},
{name:"Lista do editor",legend:"Dentro dunha lista, mÃ³vase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. MÃ³vase ao elemento anterior da lista con MAIÃšS+TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opciÃ³n da lista. Prema ESC para pechar a lista."},{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. MÃ³vase ao seguinte elemento botÃ³n con TAB ou FRECHA DEREITA. MÃ³vase ao botÃ³n anterior con MAIÃšS+TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},
{name:"Ordes",items:[{name:"Orde Â«desfacerÂ»",legend:"Prema ${undo}"},{name:"Orde Â«refacerÂ»",legend:"Prema ${redo}"},{name:"Orde Â«negraÂ»",legend:"Prema ${bold}"},{name:"Orde Â«cursivaÂ»",legend:"Prema ${italic}"},{name:"Orde Â«subliÃ±arÂ»",legend:"Prema ${underline}"},{name:"Orde Â«ligazÃ³nÂ»",legend:"Prema ${link}"},{name:"Orde Â«contraer a barra de ferramentasÂ»",legend:"Prema ${toolbarCollapse}"},{name:"Orde Â«acceder ao anterior espazo en focoÂ»",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mÃ¡is prÃ³ximo de foco inalcanzÃ¡bel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciÃ³n de teclas para chegar a espazos de foco distantes."},
{name:"Orde Â«acceder ao seguinte espazo en focoÂ»",legend:"Prema ${accessNextSpace} para acceder ao espazo mÃ¡is prÃ³ximo de foco inalcanzÃ¡bel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciÃ³n de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}],backspace:"Ir atrÃ¡s",tab:"Tabulador",enter:"Intro",shift:"MaiÃºs",ctrl:"Ctrl",alt:"Alt",pause:"Pausa",capslock:"Bloq. MaiÃºs",escape:"Escape",pageUp:"PÃ¡xina arriba",
pageDown:"PÃ¡xina abaixo",end:"Fin",home:"Inicio",leftArrow:"Frecha esquerda",upArrow:"Frecha arriba",rightArrow:"Frecha dereita",downArrow:"Frecha abaixo",insert:"Inserir","delete":"Supr",leftWindowKey:"Tecla Windows esquerda",rightWindowKey:"Tecla Windows dereita",selectKey:"Escolla a tecla",numpad0:"Tec. numÃ©rico 0",numpad1:"Tec. numÃ©rico 1",numpad2:"Tec. numÃ©rico 2",numpad3:"Tec. numÃ©rico 3",numpad4:"Tec. numÃ©rico 4",numpad5:"Tec. numÃ©rico 5",numpad6:"Tec. numÃ©rico 6",numpad7:"Tec. numÃ©rico 7",
numpad8:"Tec. numÃ©rico 8",numpad9:"Tec. numÃ©rico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Bloq. num.",scrollLock:"Bloq. despraz.",semiColon:"Punto e coma",equalSign:"Signo igual",comma:"Coma",dash:"GuiÃ³n",period:"Punto",forwardSlash:"Barra inclinada",graveAccent:"Acento grave",openBracket:"Abrir corchete",backSlash:"Barra invertida",
closeBracket:"Pechar corchete",singleQuote:"ComiÃ±a simple"});
