/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","he",{title:"×”×•×¨××•×ª × ×’×™×©×•×ª",contents:"×”×•×¨××•×ª × ×’×™×©×•×ª. ×œ×¡×’×™×¨×” ×œ×—×¥ ××¡×§×™×™×¤ (ESC).",legend:[{name:"×›×œ×œ×™",items:[{name:"×¡×¨×’×œ ×”×›×œ×™×",legend:"×œ×—×¥ ×¢×œ ${toolbarFocus} ×›×“×™ ×œ× ×•×•×˜ ×œ×¡×¨×’×œ ×”×›×œ×™×. ×¢×‘×•×¨ ×œ×›×¤×ª×•×¨ ×”×‘× ×¢× ×ž×§×© ×”×˜××‘ (TAB) ××• ×—×¥ ×©×ž××œ×™. ×¢×‘×•×¨ ×œ×›×¤×ª×•×¨ ×”×§×•×“× ×¢× ×ž×§×© ×”×©×™×¤×˜ (SHIFT) + ×˜××‘ (TAB) ××• ×—×¥ ×™×ž× ×™. ×œ×—×¥ ×¨×•×•×— ××• ×× ×˜×¨ (ENTER) ×›×“×™ ×œ×”×¤×¢×™×œ ××ª ×”×›×¤×ª×•×¨ ×”× ×‘×—×¨."},{name:"×“×™××œ×•×’×™× (×—×œ×•× ×•×ª ×ª×©××•×œ)",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"×ª×¤×¨×™×˜ ×”×”×§×©×¨ (Context Menu)",legend:"×œ×—×¥ ${contextMenu} ××• APPLICATION KEY×›×“×™ ×œ×¤×ª×•×— ××ª ×ª×¤×¨×™×˜ ×”×”×§×©×¨. ×¢×‘×•×¨ ×œ××¤×©×¨×•×ª ×”×‘××” ×¢× ×˜××‘ (TAB) ××• ×—×¥ ×œ×ž×˜×”. ×¢×‘×•×¨ ×œ××¤×©×¨×•×ª ×”×§×•×“×ž×ª ×¢× ×©×™×¤×˜ (SHIFT) + ×˜××‘ (TAB) ××• ×—×¥ ×œ×ž×¢×œ×”. ×œ×—×¥ ×¨×•×•×— ××• ×× ×˜×¨ (ENTER) ×›×“×™ ×œ×‘×—×•×¨ ××ª ×”××¤×©×¨×•×ª. ×¤×ª×— ××ª ×ª×ª ×”×ª×¤×¨×™×˜ (Sub-menu) ×©×œ ×”××¤×©×¨×•×ª ×”× ×•×›×—×™×ª ×¢× ×¨×•×•×— ××• ×× ×˜×¨ (ENTER) ××• ×—×¥ ×©×ž××œ×™. ×—×–×•×¨ ×œ×ª×¤×¨×™×˜ ×”××‘ ×¢× ××¡×§×™×™×¤ (ESC) ××• ×—×¥ ×©×ž××œ×™. ×¡×’×•×¨ ××ª ×ª×¤×¨×™×˜ ×”×”×§×©×¨ ×¢× ××¡×§×™×™×¤ (ESC)."},{name:"×ª×¤×¨×™×˜×™× ×¦×¤×™× (List boxes)",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"×¢×¥ ××œ×ž× ×˜×™× (Elements Path)",legend:"×œ×—×¥ ${elementsPathFocus} ×›×“×™ ×œ× ×•×•×˜ ×œ×¢×¥ ×”××œ×ž× ×˜×™×. ×¢×‘×•×¨ ×œ×¤×¨×™×˜ ×”×‘× ×¢× ×˜××‘ (TAB) ××• ×—×¥ ×™×ž× ×™. ×¢×‘×•×¨ ×œ×¤×¨×™×˜ ×”×§×•×“× ×¢× ×©×™×¤×˜ (SHIFT) + ×˜××‘ (TAB) ××• ×—×¥ ×©×ž××œ×™. ×œ×—×¥ ×¨×•×•×— ××• ×× ×˜×¨ (ENTER) ×›×“×™ ×œ×‘×—×•×¨ ××ª ×”××œ×ž× ×˜ ×‘×¢×•×¨×š."}]},{name:"×¤×§×•×“×•×ª",items:[{name:" ×‘×™×˜×•×œ ×¦×¢×“ ××—×¨×•×Ÿ",legend:"×œ×—×¥ ${undo}"},{name:" ×—×–×¨×” ×¢×œ ×¦×¢×“ ××—×¨×•×Ÿ",legend:"×œ×—×¥ ${redo}"},{name:" ×”×“×’×©×”",legend:"×œ×—×¥ ${bold}"},{name:" ×”×˜×™×™×”",legend:"×œ×—×¥ ${italic}"},{name:" ×”×•×¡×¤×ª ×§×• ×ª×—×ª×•×Ÿ",legend:"×œ×—×¥ ${underline}"},{name:" ×”×•×¡×¤×ª ×œ×™× ×§",
legend:"×œ×—×¥ ${link}"},{name:" ×›×™×•×•×¥ ×¡×¨×’×œ ×”×›×œ×™×",legend:"×œ×—×¥ ${toolbarCollapse}"},{name:"×’×™×©×” ×œ×ž×™×§×•× ×”×ž×™×§×•×“ ×”×§×•×“×",legend:"×œ×—×¥ ${accessPreviousSpace} ×›×“×™ ×œ×’×©×ª ×œ×ž×™×§×•× ×”×ž×™×§×•×“ ×”×œ×-× ×’×™×© ×”×§×¨×•×‘ ×œ×¤× ×™ ×”×¡×ž×Ÿ, ×œ×ž×©×œ ×‘×™×Ÿ ×©× ×™ ××œ×ž× ×˜×™× ×¡×ž×•×›×™× ×ž×¡×•×’ HR. ×—×–×•×¨ ×¢×œ ×¦×™×¨×•×£ ×ž×§×©×™× ×–×” ×›×“×™ ×œ×”×’×™×¢ ×œ×ž×§×•×ž×•×ª ×ž×™×§×•×“ ×¨×—×•×§×™× ×™×•×ª×¨."},{name:"×’×™×©×” ×œ×ž×™×§×•× ×”×ž×™×§×•×“ ×”×‘×",legend:"×œ×—×¥ ${accessNextSpace} ×›×“×™ ×œ×’×©×ª ×œ×ž×™×§×•× ×”×ž×™×§×•×“ ×”×œ×-× ×’×™×© ×”×§×¨×•×‘ ××—×¨×™ ×”×¡×ž×Ÿ, ×œ×ž×©×œ ×‘×™×Ÿ ×©× ×™ ××œ×ž× ×˜×™× ×¡×ž×•×›×™× ×ž×¡×•×’ HR. ×—×–×•×¨ ×¢×œ ×¦×™×¨×•×£ ×ž×§×©×™× ×–×” ×›×“×™ ×œ×”×’×™×¢ ×œ×ž×§×•×ž×•×ª ×ž×™×§×•×“ ×¨×—×•×§×™× ×™×•×ª×¨."},
{name:" ×”×•×¨××•×ª × ×’×™×©×•×ª",legend:"×œ×—×¥ ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"×—×¥ ×©×ž××œ×”",upArrow:"×—×¥ ×œ×ž×¢×œ×”",rightArrow:"×—×¥ ×™×ž×™× ×”",downArrow:"×—×¥ ×œ×ž×˜×”",insert:"×”×›× ×¡","delete":"×ž×—×§",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"×‘×—×¨ ×ž×§×©",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",
numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"×”×•×¡×£",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"×¡×œ××©",graveAccent:"Grave Accent",
openBracket:"Open Bracket",backSlash:"×¡×œ××© ×”×¤×•×š",closeBracket:"Close Bracket",singleQuote:"×¦×™×˜×•×˜ ×™×—×™×“"});
