/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","km",{title:"Accessibility Instructions",contents:"áž˜áž¶ážáž·áž€áž¶â€‹áž‡áŸ†áž“áž½áž™áŸ” ážŠáž¾áž˜áŸ’áž”áž¸â€‹áž”áž·áž‘â€‹áž•áŸ’áž‘áž¶áŸ†áž„â€‹áž“áŸáŸ‡ ážŸáž¼áž˜â€‹áž…áž»áž… ESC áŸ”",legend:[{name:"áž‘áž¼áž‘áŸ…",items:[{name:"ážšáž”áž¶ážšâ€‹áž§áž”áž€ážšážŽáŸâ€‹áž€áž˜áŸ’áž˜ážœáž·áž’áž¸â€‹áž“áž·áž–áž“áŸ’áž’",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"áž•áŸ’áž‘áž¶áŸ†áž„â€‹áž€áž˜áŸ’áž˜ážœáž·áž’áž¸áž“áž·áž–áž“áŸ’áž’",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"áž˜áŸ‰áž¸áž“áž»áž™áž”ážšáž·áž”áž‘áž¢áŸ’áž“áž€áž€áŸ‚ážŸáž˜áŸ’ážšáž½áž›",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"áž”áŸ’ážšáž¢áž”áŸ‹áž”áž‰áŸ’áž‡áž¸áž¢áŸ’áž“áž€áž€áŸ‚ážŸáž˜áŸ’ážšáž½áž›",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"áž–áž¶áž€áŸ’áž™áž”áž‰áŸ’áž‡áž¶",items:[{name:"áž€áž¶ážšâ€‹áž”áž‰áŸ’áž‡áž¶â€‹áž˜áž·áž“áž’áŸ’ážœáž¾ážœáž·áž‰",legend:"áž…áž»áž… ${undo}"},{name:"áž€áž¶ážšáž”áž‰áŸ’áž‡áž¶â€‹áž’áŸ’ážœáž¾ážœáž·áž‰",legend:"áž…áž»áž… ${redo}"},{name:"áž€áž¶ážšáž”áž‰áŸ’áž‡áž¶â€‹áž¢áž€áŸ’ážŸážšâ€‹ážŠáž·áž",legend:"áž…áž»áž… ${bold}"},{name:"áž€áž¶ážšáž”áž‰áŸ’áž‡áž¶â€‹áž¢áž€áŸ’ážŸážšâ€‹áž‘áŸ’ážšáŸáž",legend:"áž…áž»áž… ${italic}"},{name:"áž–áž¶áž€áŸ’áž™áž”áž‰áŸ’áž‡áž¶â€‹áž”áž“áŸ’áž‘áž¶ážáŸ‹â€‹áž–áž¸áž€áŸ’ážšáŸ„áž˜",
legend:"áž…áž»áž… ${underline}"},{name:"áž–áž¶áž€áŸ’áž™áž”áž‰áŸ’áž‡áž¶â€‹ážáŸ†ážŽ",legend:"áž…áž»áž… ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"áž‡áŸ†áž“áž½áž™â€‹áž–áž¸â€‹áž—áž¶áž–â€‹áž„áž¶áž™ážŸáŸ’ážšáž½áž›",legend:"áž‡áž½áž™ ${a11yHelp}"}]}],backspace:"áž›áž»áž”ážáž™áž€áŸ’ážšáŸ„áž™",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"áž•áŸ’áž¢áž¶áž€",capslock:"Caps Lock",escape:"áž…áž¶áž€áž…áŸáž‰",pageUp:"áž‘áŸ†áž–áŸážšâ€‹áž›áž¾",pageDown:"áž‘áŸ†áž–áŸážšâ€‹áž€áŸ’ážšáŸ„áž˜",end:"áž…áž»áž„",home:"áž•áŸ’áž‘áŸ‡",leftArrow:"áž–áŸ’ážšáž½áž‰â€‹áž†áŸ’ážœáŸáž„",upArrow:"áž–áŸ’ážšáž½áž‰â€‹áž›áž¾",rightArrow:"áž–áŸ’ážšáž½áž‰â€‹ážŸáŸ’ážŠáž¶áŸ†",downArrow:"áž–áŸ’ážšáž½áž‰â€‹áž€áŸ’ážšáŸ„áž˜",insert:"áž”áž‰áŸ’áž…áž¼áž›","delete":"áž›áž»áž”",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"áž‡áŸ’ážšáž¾ážŸâ€‹áž‚áŸ’ážšáž¶áž”áŸ‹â€‹áž…áž»áž…",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"áž‚áž»ážŽ",add:"áž”áž“áŸ’ážáŸ‚áž˜",subtract:"ážŠáž€",decimalPoint:"áž…áŸ†ážŽáž»áž…áž‘ážŸáž—áž¶áž‚",divide:"áž…áŸ‚áž€",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"áž”áž·áž‘â€‹ážšáŸ†áž€áž·áž›",semiColon:"áž…áž»áž…â€‹áž€áŸ’áž”áŸ€ážŸ",equalSign:"ážŸáž‰áŸ’áž‰áž¶â€‹áž¢ážºážšáŸ‰áž¼",comma:"áž€áŸ’áž”áŸ€ážŸ",dash:"Dash",period:"áž…áž»áž…",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",
openBracket:"ážáž„áŸ’áž€áŸ€áž”â€‹áž”áž¾áž€",backSlash:"Backslash",closeBracket:"ážáž„áŸ’áž€áŸ€áž”â€‹áž”áž·áž‘",singleQuote:"áž”áž“áŸ’ážáž€áŸ‹â€‹áž˜áž½áž™"});
