/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ku",{title:"Ú•ÛŽÙ†Ù…Ø§ÛŒ Ù„Û•Ø¨Û•Ø±Ø¯Û•Ø³ØªØ¯Ø§Ø¨ÙˆÙˆÙ†",contents:"Ù¾ÛŽÚ©Ù‡Ø§ØªÛ•ÛŒ ÛŒØ§Ø±Ù…Û•ØªÛŒ. Ú©Ù„ÛŒÙƒ ESC Ø¨Û† Ø¯Ø§Ø®Ø³ØªÙ†ÛŒ Ø¦Û•Ù… Ø¯ÛŒØ§Ù„Û†Ú¯Ù‡.",legend:[{name:"Ú¯Ø´ØªÛŒ",items:[{name:"ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²ÛŒ Ø¯Û•Ø³ØªÙƒØ§Ø±ÛŒÙƒÛ•Ø±",legend:"Ú©Ù„ÛŒÙƒ ${toolbarFocus} Ø¨Û† Ú•Ø§Ø¨Û•Ø±ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø². Ø¨Û† Ú¯ÙˆØ§Ø³ØªÙ†Û•ÙˆÛ•ÛŒ Ù¾ÛŽØ´ÙˆÙˆ Ø¯Ø§Ù‡Ø§ØªÙˆÙˆÛŒ Ú¯Ø±ÙˆÙˆÙ¾ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²ÛŒ Ø¯Ø§Ú¯Ø±ØªÙ†ÛŒ Ú©Ù„ÛŒÙ„ÛŒ TAB Ù„Û•Ú¯Û•Úµâ€Œ SHIFT+TAB. Ø¨Û† Ú¯ÙˆØ§Ø³ØªÙ†Û•ÙˆÛ•ÛŒ Ù¾ÛŽØ´ÙˆÙˆ Ø¯Ø§Ù‡Ø§ØªÙˆÙˆÛŒ Ø¯ÙˆÙˆÚ¯Ù…Û•ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²ÛŒ Ù„Û•Ú•ÛŽÛŒ Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú•Ø§Ø³Øª ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú†Û•Ù¾. Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SPACE ÛŒØ§Ù† ENTER Ø¨Û† Ú†Ø§Ù„Ø§Ú©Ú©Ø±Ø¯Ù†ÛŒ Ø¯ÙˆÙˆÚ¯Ù…Û•ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²."},{name:"Ø¯ÛŒØ§Ù„Û†Ú¯ÛŒ Ø¯Û•Ø³ØªÙƒØ§Ø±ÛŒÙƒÛ•Ø±",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Ù¾ÛŽÚ•Ø³ØªÛŒ Ø³Û•Ø±Ù†ÙˆÙˆØ³Û•Ø±",legend:"Ú©Ù„ÛŒÙƒ ${contextMenu} ÛŒØ§Ù† Ø¯ÙˆÚ¯Ù…Û•ÛŒ Ù„ÛŒØ³ØªÙ‡â€Œ(Menu) Ø¨Û† Ú©Ø±Ø¯Ù†Û•ÙˆÛ•ÛŒ Ù„ÛŒØ³ØªÛ•ÛŒ Ø¯Û•Ù‚. Ø¨Û† Ú†ÙˆÙˆÙ†Û• Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒÛ•Ú©ÛŒ ØªØ± Ù„Ù‡â€Œ Ù„ÛŒØ³ØªÙ‡â€Œ Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ TAB ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ú•ÙˆÙˆ Ù„Û•Ø®ÙˆØ§Ø±Û•ÙˆÙ‡â€Œ Ø¨Û† Ú†ÙˆÙˆÙ† Ø¨Û† Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù¾ÛŽØ´ÙˆÙˆ Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SHIFT+TAB ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ú•ÙˆÙˆ Ù„Ù‡â€Œ Ø³Û•Ø±Û•ÙˆÛ•. Ø¯Ø§Ú¯Ø±ØªÙ†ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SPACE ÛŒØ§Ù† ENTER Ø¨Û† Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Ù†ÛŒ Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù„ÛŒØ³ØªÙ‡â€Œ. Ø¨Û† Ú©Ø±Ø¯Ù†Û•ÙˆÛ•ÛŒ Ù„Ù‚ÛŒ Ú˜ÛŽØ± Ù„ÛŒØ³ØªÙ‡â€Œ Ù„Û•Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù„ÛŒØ³ØªÛ• Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SPACE ÛŒØ§Ù† ENTER ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú•Ø§Ø³Øª. Ø¨Û† Ú¯Û•Ú•Ø§Ù†Û•ÙˆÙ‡ Ø¨Û† Ø³Û•Ø±Û•ÙˆÛ•ÛŒ Ù„ÛŒØ³ØªÙ‡â€Œ Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ ESC ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú†Û•Ù¾. Ø¨Û† Ø¯Ø§Ø®Ø³ØªÙ†ÛŒ Ù„ÛŒØ³ØªÛ• Ú©Ù„ÛŒÙƒÛŒ Ú©Ù„ÛŒÙ„ÛŒ ESC Ø¨Ú©Û•."},
{name:"Ù„ÛŒØ³ØªÛŒ Ø³Ù†ÙˆÙˆÙ‚ÛŒ Ø³Û•Ø±Ù†ÙˆÙˆØ³Û•Ø±",legend:"Ù„Û•Ù†Ø§Ùˆ Ø³Ù†ÙˆÙ‚ÛŒ Ù„ÛŒØ³Øª, Ú†Û†Ù† Ø¨Û† Ù‡Û•ÚµÙ†Ø¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù„ÛŒØ³ØªÛŽÚ©ÛŒ ØªØ± Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ TAB ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ú•ÙˆÙˆ Ù„Û•Ø®ÙˆØ§Ø±. Ú†ÙˆÙˆÙ† Ø¨Û† Ù‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù„ÛŒØ³ØªÛŒ Ù¾ÛŽØ´ÙˆÙˆ Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SHIFT+TAB ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ú•ÙˆÙˆ Ù„Û•Ø³Û•Ø±Û•ÙˆÙ‡â€Œ. Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SPACE ÛŒØ§Ù† ENTER Ø¨Û† Ø¯ÛŒØ§Ø±ÛŒÚ©Ø±Ø¯Ù†ÛŒ â€ŒÙ‡Û•ÚµØ¨Ú˜Ø§Ø±Ø¯Û•ÛŒ Ù„ÛŒØ³Øª. Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ ESC Ø¨Û† Ø¯Ø§Ø®Ø³ØªÙ†ÛŒ Ø³Ù†ÙˆÙ‚ÛŒ Ù„ÛŒØ³Øª."},{name:"ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²ÛŒ ØªÙˆØ®Ù…",legend:"Ú©Ù„ÛŒÙƒ ${elementsPathFocus} Ø¨Û† Ú•Ø§Ø¨Û•Ø±ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²ÛŒ ØªÙˆØ®Ù…Û•Ú©Ø§Ù†. Ú†ÙˆÙˆÙ† Ø¨Û† Ø¯ÙˆÚ¯Ù…Û•ÛŒ ØªÙˆØ®Ù…ÛŽÚ©ÛŒ ØªØ± Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ TAB ÛŒØ§Ù† Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú•Ø§Ø³Øª. Ú†ÙˆÙˆÙ† Ø¨Û† Ø¯ÙˆÚ¯Ù…Û•ÛŒ ØªÙˆØ®Ù…ÛŒ Ù¾ÛŽØ´ÙˆÙˆ Ú©Ù„ÛŒÙ„ÛŒ SHIFT+TAB ÛŒØ§Ù† Ú©Ù„ÛŒÚ©ÛŒ Ú©Ù„ÛŒÙ„ÛŒ ØªÛŒØ±ÛŒ Ø¯Û•Ø³ØªÛŒ Ú†Û•Ù¾. Ø¯Ø§Ú¯Ø±ØªÙ†ÛŒ Ú©Ù„ÛŒÙ„ÛŒ SPACE ÛŒØ§Ù† ENTER Ø¨Û† Ø¯ÛŒØ§Ø±ÛŒÚ©Ø±Ø¯Ù†ÛŒ ØªÙˆØ®Ù…Û•Ú©Ù‡â€Œ Ù„Û•Ø³Û•Ø±Ù†ÙˆÙˆØ³Ù‡."}]},
{name:"ÙÛ•Ø±Ù…Ø§Ù†Û•Ú©Ø§Ù†",items:[{name:"Ù¾ÙˆÙˆÚ†Ú©Ø±Ø¯Ù†Û•ÙˆÛ•ÛŒ ÙÛ•Ø±Ù…Ø§Ù†",legend:"Ú©Ù„ÛŒÙƒ ${undo}"},{name:"Ù‡Û•ÚµÚ¯Û•Ú•Ø§Ù†Û•ÙˆÛ•ÛŒ ÙÛ•Ø±Ù…Ø§Ù†",legend:"Ú©Ù„ÛŒÙƒ ${redo}"},{name:"ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ø¯Û•Ù‚ÛŒ Ù‚Û•ÚµÛ•Ùˆ",legend:"Ú©Ù„ÛŒÙƒ ${bold}"},{name:"ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ø¯Û•Ù‚ÛŒ Ù„Ø§Ø±",legend:"Ú©Ù„ÛŒÙƒ ${italic}"},{name:"ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ú˜ÛŽØ±Ù‡ÛŽÚµ",legend:"Ú©Ù„ÛŒÙƒ ${underline}"},{name:"ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ø¨Ù‡â€ŒØ³ØªÛ•Ø±",legend:"Ú©Ù„ÛŒÙƒ ${link}"},{name:"Ø´Ø§Ø±Ø¯Û•Ù†Û•ÙˆÛ•ÛŒ ØªÙˆÙˆÚµØ§Ù…Ø±Ø§Ø²",legend:"Ú©Ù„ÛŒÙƒ ${toolbarCollapse}"},{name:"Ú†ÙˆÙˆÙ†Û•Ù†Ø§Ùˆ Ø³Û•Ø±Ù†Ø¬Ø¯Ø§Ù†ÛŒ Ù¾ÛŽØ´ÙˆÛŒ ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ø¨Û†Ø´Ø§ÛŒÛŒ",legend:"Ú©Ù„ÛŒÚ© ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"Ú†ÙˆÙˆÙ†Û•Ù†Ø§Ùˆ Ø³Û•Ø±Ù†Ø¬Ø¯Ø§Ù†ÛŒ Ø¯Ø§Ù‡Ø§ØªÙˆÙˆÛŒ ÙÛ•Ø±Ù…Ø§Ù†ÛŒ Ø¨Û†Ø´Ø§ÛŒÛŒ",legend:"Ú©Ù„ÛŒÚ© ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Ø¯Û•Ø³ØªÙ¾ÛŽÚ¯Û•ÛŒØ´ØªÙ†ÛŒ ÛŒØ§Ø±Ù…Û•ØªÛŒ",legend:"Ú©Ù„ÛŒÙƒ ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",
upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Ù¾Û•Ù†Ø¬Û•Ø±Û•ÛŒ Ú†Û•Ù¾",rightWindowKey:"Ù¾Û•Ù†Ø¬Û•Ø±Û•ÛŒ Ú•Ø§Ø³Øª",selectKey:"Select",numpad0:"Numpad 0",numpad1:"1",numpad2:"2",numpad3:"3",numpad4:"4",numpad5:"5",numpad6:"6",numpad7:"7",numpad8:"8",numpad9:"9",multiply:"*",add:"+",subtract:"-",decimalPoint:".",divide:"/",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",
semiColon:";",equalSign:"\x3d",comma:",",dash:"-",period:".",forwardSlash:"/",graveAccent:"`",openBracket:"[",backSlash:"\\\\",closeBracket:"}",singleQuote:"'"});
