/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","no",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for Ã¥ lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"VerktÃ¸ylinje for editor",legend:"Trykk ${toolbarFocus} for Ã¥ navigere til verktÃ¸ylinjen. Flytt til neste og forrige verktÃ¸ylinjegruppe med TAB og SHIFT+TAB. Flytt til neste og forrige verktÃ¸ylinjeknapp med HÃ˜YRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Ã¥ aktivere verktÃ¸ylinjeknappen."},{name:"Dialog for editor",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for Ã¥ Ã¥pne kontekstmeny. GÃ¥ til neste alternativ i menyen med TAB eller PILTAST NED. GÃ¥ til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Ã¥ velge menyalternativet. Ã…pne undermenyen pÃ¥ valgt alternativ med MELLOMROM eller ENTER eller HÃ˜YRE PILTAST. GÃ¥ tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, gÃ¥ til neste alternativ i listen med TAB eller PILTAST NED. GÃ¥ til forrige alternativ i listen med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Ã¥ velge alternativet i listen. Trykk ESC for Ã¥ lukke listeboksen."},{name:"VerktÃ¸ylinje for elementsti",legend:"Trykk ${elementsPathFocus} for Ã¥ navigere til verktÃ¸ylinjen som viser elementsti. GÃ¥ til neste elementknapp med TAB eller HÃ˜YRE PILTAST. GÃ¥ til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Ã¥ velge elementet i editoren."}]},
{name:"Kommandoer",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"GjÃ¸r om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Link",legend:"Trykk ${link}"},{name:"Skjul verktÃ¸ylinje",legend:"Trykk ${toolbarCollapse}"},{name:"GÃ¥ til forrige fokusomrÃ¥de",legend:"Trykk ${accessPreviousSpace} for Ã¥ komme til nÃ¦rmeste fokusomrÃ¥de fÃ¸r skrivemarkÃ¸ren som ikke kan nÃ¥s pÃ¥ vanlig mÃ¥te, for eksempel to tilstÃ¸tende HR-elementer. Gjenta tastekombinasjonen for Ã¥ komme til fokusomrÃ¥der lenger unna i dokumentet."},
{name:"GÃ¥ til neste fokusomrÃ¥de",legend:"Trykk ${accessNextSpace} for Ã¥ komme til nÃ¦rmeste fokusomrÃ¥de etter skrivemarkÃ¸ren som ikke kan nÃ¥s pÃ¥ vanlig mÃ¥te, for eksempel to tilstÃ¸tende HR-elementer. Gjenta tastekombinasjonen for Ã¥ komme til fokusomrÃ¥der lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});
