/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"InstrucÈ›iuni de accesibilitate",contents:"Cuprins. Pentru a Ã®nchide acest dialog, apÄƒsaÈ›i tasta ESC.",legend:[{name:"General",items:[{name:"EditeazÄƒ bara instrumente.",legend:"ApasÄƒ ${toolbarFocus} pentru a naviga prin bara de instrumente. Pentru a te miÈ™ca prin grupurile de instrumente foloseÈ™te tastele TAB È™i SHIFT+TAB. Pentru a te miÈ™ca intre diverse instrumente foloseÈ™te tastele SÄ‚GEATÄ‚ DREAPTA sau SÄ‚GEATÄ‚ STÃ‚NGA. ApasÄƒ butonul SPAÈšIU sau ENTER pentru activarea instrumentului."},
{name:"Dialog editor",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor meniu contextual",legend:"ApasÄƒ ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Treci la urmÄƒtoarea opÈ›iune din meniu cu TAB sau SÄ‚GEATÄ‚ JOS. Treci la opÈ›iunea anterioarÄƒ cu  SHIFT+TAB sau SÄ‚GEATÄ‚ SUS. ApasÄƒ SPAÈšIU sau ENTER pentru a selecta opÈ›iunea din meniu. Deschide sub-meniul opÈ›iunii curente cu SPAÈšIU sau ENTER sau SÄ‚GEATÄ‚ DREAPTA. Revino la elementul din meniul pÄƒrinte cu ESC sau SÄ‚GEATÄ‚ STÃ‚NGA. ÃŽnchide meniul de context cu ESC."},
{name:"Editor CasetÄƒ ListÄƒ",legend:"ÃŽn interiorul unei liste, treci la urmÄƒtorull element cu TAB sau SÄ‚GEATÄ‚ JOS. Treci la elementul anterior din listÄƒ cu SHIFT+TAB sau SÄ‚GEATÄ‚ SUS. ApasÄƒ SPAÈšIU sau ENTER pentru a selecta opÈ›iunea din listÄƒ. ApasÄƒ ESC pentru a Ã®nchide lista."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"Comenzi",items:[{name:" Undo command",legend:"ApasÄƒ ${undo}"},{name:"Comanda precedentÄƒ",legend:"ApasÄƒ ${redo}"},{name:"Comanda ÃŽngroÈ™at",legend:"ApasÄƒ ${bold}"},{name:"Comanda Inclinat",legend:"ApasÄƒ ${italic}"},{name:"Comanda Subliniere",legend:"ApasÄƒ ${underline}"},{name:"Comanda LegaturÄƒ",legend:"ApasÄƒ ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",
upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",
f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});
