/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"InÅ¡trukcie prÃ­stupnosti",contents:"PomocnÃ½ obsah. Pre zatvorenie tohto okna, stlaÄte ESC.",legend:[{name:"VÅ¡eobecne",items:[{name:"LiÅ¡ta nÃ¡strojov editora",legend:"StlaÄte ${toolbarFocus} pre navigÃ¡ciu na liÅ¡tu nÃ¡strojov. Medzi ÄalÅ¡ou a predchÃ¡dzajÃºcou liÅ¡tou nÃ¡strojov sa pohybujete s TAB a SHIFT+TAB. Medzi ÄalÅ¡Ã­m a predchÃ¡dzajÃºcim tlaÄidlom na liÅ¡te nÃ¡strojov sa pohybujete s pravou Å¡Ã­pkou a Ä¾avou Å¡Ã­pkou. StlaÄte medzernÃ­k alebo ENTER pre aktivÃ¡ciu tlaÄidla liÅ¡ty nÃ¡strojov."},
{name:"EditorovÃ½ dialÃ³g",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"EditorovÃ© kontextovÃ© menu",legend:"StlaÄte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextovÃ©ho menu. Potom sa presÃºvajte na ÄalÅ¡ie moÅ¾nosti menu s TAB alebo dolnou Å¡Ã­pkou. Presunte sa k predchÃ¡dzajÃºcej moÅ¾nosti s SHIFT+TAB alebo hornou Å¡Ã­pkou. StlaÄte medzernÃ­k alebo ENTER pre vÃ½ber moÅ¾nosti menu. Otvorte pod-menu danej moÅ¾nosti s medzernÃ­kom, alebo ENTER, alebo pravou Å¡Ã­pkou. VrÃ¡Å¥te sa spÃ¤Å¥ do poloÅ¾ky rodiÄovskÃ©ho menu s ESC alebo Ä¾avou Å¡Ã­pkou. Zatvorte kontextovÃ© menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuÅˆte sa na ÄalÅ¡iu poloÅ¾ku v zozname s TAB alebo dolnou Å¡Ã­pkou. PresuÅˆte sa k predchÃ¡dzajÃºcej poloÅ¾ke v zozname so SHIFT+TAB alebo hornou Å¡Ã­pkou. StlaÄte medzernÃ­k alebo ENTER pre vÃ½ber moÅ¾nosti zoznamu. StlaÄte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pÃ¡smo cesty prvku",legend:"StlaÄte ${elementsPathFocus} pre navigovanie na pÃ¡smo cesty elementu. PresuÅˆte sa na tlaÄidlo ÄalÅ¡ieho prvku s TAB alebo pravou Å¡Ã­pkou. PresuÅˆte sa k predchÃ¡dzajÃºcemu tlaÄidlu s SHIFT+TAB alebo Ä¾avou Å¡Ã­pkou. StlaÄte medzernÃ­k alebo ENTER pre vÃ½ber prvku v editore."}]},
{name:"PrÃ­kazy",items:[{name:"VrÃ¡tiÅ¥ prÃ­kazy",legend:"StlaÄte ${undo}"},{name:"Nanovo vrÃ¡tiÅ¥ prÃ­kaz",legend:"StlaÄte ${redo}"},{name:"PrÃ­kaz na stuÄnenie",legend:"StlaÄte ${bold}"},{name:"PrÃ­kaz na kurzÃ­vu",legend:"StlaÄte ${italic}"},{name:"PrÃ­kaz na podÄiarknutie",legend:"StlaÄte ${underline}"},{name:"PrÃ­kaz na odkaz",legend:"StlaÄte ${link}"},{name:"PrÃ­kaz na zbalenie liÅ¡ty nÃ¡strojov",legend:"StlaÄte ${toolbarCollapse}"},{name:"PrejsÅ¥ na predchÃ¡dzajÃºcu zamerateÄ¾nÃº medzeru prÃ­kazu",legend:"StlaÄte ${accessPreviousSpace} pre prÃ­stup na najbliÅ¾Å¡ie nedosiahnuteÄ¾nÃ© zamerateÄ¾nÃ© medzery pred vsuvkuo. NaprÃ­klad: dve za sebou idÃºce horizontÃ¡lne Äiary. Opakujte kombinÃ¡ciu klÃ¡vesov pre dosiahnutie vzdialenÃ½ch zamerateÄ¾nÃ½ch medzier."},
{name:"PrejsÅ¥ na ÄalÅ¡Ã­ ",legend:"StlaÄte ${accessNextSpace} pre prÃ­stup na najbliÅ¾Å¡ie nedosiahnuteÄ¾nÃ© zamerateÄ¾nÃ© medzery po vsuvke. NaprÃ­klad: dve za sebou idÃºce horizontÃ¡lne Äiary. Opakujte kombinÃ¡ciu klÃ¡vesov pre dosiahnutie vzdialenÃ½ch zamerateÄ¾nÃ½ch medzier."},{name:"Pomoc prÃ­stupnosti",legend:"StlaÄte ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"StrÃ¡nka hore",pageDown:"StrÃ¡nka dole",
end:"End",home:"Home",leftArrow:"Å Ã­pka naÄ¾avo",upArrow:"Å Ã­pka hore",rightArrow:"Å Ã­pka napravo",downArrow:"Å Ã­pka dole",insert:"Insert","delete":"Delete",leftWindowKey:"Ä½avÃ© Windows tlaÄidlo",rightWindowKey:"PravÃ© Windows tlaÄidlo",selectKey:"TlaÄidlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"NÃ¡sobenie",add:"SÄÃ­tanie",subtract:"OdÄÃ­tanie",
decimalPoint:"DesatinnÃ¡ Äiarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"BodkoÄiarka",equalSign:"RovnÃ¡ sa",comma:"ÄŒiarka",dash:"PomÄºÄka",period:"Bodka",forwardSlash:"LomÃ­tko",graveAccent:"ZdÃ´razÅˆovanie prÃ­zvuku",openBracket:"HranatÃ¡ zÃ¡tvorka otvÃ¡racia",backSlash:"Backslash",closeBracket:"HranatÃ¡ zÃ¡tvorka zatvÃ¡racia",singleQuote:"JednoduchÃ© Ãºvodzovky"});
