/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"EriÅŸilebilirlik TalimatlarÄ±",contents:"YardÄ±m iÃ§eriÄŸi. Bu pencereyi kapatmak iÃ§in ESC tuÅŸuna basÄ±n.",legend:[{name:"Genel",items:[{name:"DÃ¼zenleyici AraÃ§ Ã‡ubuÄŸu",legend:"AraÃ§ Ã§ubuÄŸunda gezinmek iÃ§in ${toolbarFocus} basÄ±n. TAB ve SHIFT+TAB ile Ã¶nceki ve sonraki araÃ§ Ã§ubuÄŸu grubuna taÅŸÄ±yÄ±n. SAÄž OK veya SOL OK ile Ã¶nceki ve sonraki bir araÃ§ Ã§ubuÄŸu dÃ¼ÄŸmesini hareket ettirin. SPACE tuÅŸuna basÄ±n veya araÃ§ Ã§ubuÄŸu dÃ¼ÄŸmesini etkinleÅŸtirmek iÃ§in ENTER tuÅŸna basÄ±n."},
{name:"Diyalog DÃ¼zenleyici",legend:"Dialog penceresi iÃ§inde, sonraki iletiÅŸim alanÄ±na gitmek iÃ§in SEKME tuÅŸuna basÄ±n, Ã¶nceki alana geÃ§mek iÃ§in SHIFT + TAB tuÅŸuna basÄ±n, pencereyi gÃ¶ndermek iÃ§in ENTER tuÅŸuna basÄ±n, dialog penceresini iptal etmek iÃ§in ESC tuÅŸuna basÄ±n. Birden Ã§ok sekme sayfalarÄ± olan diyaloglarÄ±n, sekme listesine gitmek iÃ§in ALT + F10 tuÅŸlarÄ±na basÄ±n. Sonra TAB veya SAÄž OK sonraki sekmeye taÅŸÄ±yÄ±n. SHIFT + TAB veya SOL OK ile Ã¶nceki sekmeye geÃ§in. Sekme sayfayÄ± seÃ§mek iÃ§in SPACE veya ENTER tuÅŸuna basÄ±n."},
{name:"Ä°Ã§erik MenÃ¼ EditÃ¶rÃ¼",legend:"Ä°Ã§erik menÃ¼sÃ¼nÃ¼ aÃ§mak iÃ§in ${contextMenu} veya UYGULAMA TUÅžU'na basÄ±n. Daha sonra SEKME veya AÅžAÄžI OK ile bir sonraki menÃ¼ seÃ§eneÄŸi taÅŸÄ±yÄ±n. SHIFT + TAB veya YUKARI OK ile Ã¶nceki seÃ§eneÄŸe gider. MenÃ¼ seÃ§eneÄŸini seÃ§mek iÃ§in SPACE veya ENTER tuÅŸuna basÄ±n. SeÃ§ili seÃ§eneÄŸin alt menÃ¼sÃ¼nÃ¼ SPACE ya da ENTER veya SAÄž OK aÃ§Ä±n. Ãœst menÃ¼ Ã¶ÄŸesini geÃ§mek iÃ§in ESC veya SOL OK ile geri dÃ¶nÃ¼n. ESC ile baÄŸlam menÃ¼sÃ¼nÃ¼ kapatÄ±n."},{name:"Liste Kutusu EditÃ¶rÃ¼",legend:"Liste kutusu iÃ§inde, bir sonraki liste Ã¶ÄŸesine SEKME VEYA AÅžAÄžI OK ile taÅŸÄ±yÄ±n. SHIFT+TAB veya YUKARI Ã¶nceki liste Ã¶ÄŸesi taÅŸÄ±yÄ±n. Liste seÃ§eneÄŸi seÃ§mek iÃ§in SPACE veya ENTER tuÅŸuna basÄ±n. Liste kutusunu kapatmak iÃ§in ESC tuÅŸuna basÄ±n."},
{name:"Element Yol Ã‡ubuÄŸu EditÃ¶rÃ¼",legend:"Elementlerin yol Ã§ubuÄŸunda gezinmek iÃ§in ${ElementsPathFocus} basÄ±n. SEKME veya SAÄž OK ile sonraki element dÃ¼ÄŸmesine taÅŸÄ±yÄ±n. SHIFT+TAB veya SOL OK Ã¶nceki dÃ¼ÄŸmeye hareket ettirin. EditÃ¶r iÃ§indeki elementi seÃ§mek iÃ§in ENTER veya SPACE tuÅŸuna basÄ±n."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basÄ±n"},{name:"Komutu geri al",legend:"${redo} basÄ±n"},{name:" KalÄ±n komut",legend:"${bold} basÄ±n"},{name:" Ä°talik komutu",legend:"${italic} basÄ±n"},
{name:" Alttan Ã§izgi komutu",legend:"${underline} basÄ±n"},{name:" BaÄŸlantÄ± komutu",legend:"${link} basÄ±n"},{name:" AraÃ§ Ã§ubuÄŸu Toplama komutu",legend:"${toolbarCollapse} basÄ±n"},{name:"Ã–nceki komut alanÄ±na odaklan",legend:"DÃ¼zeltme imleÃ§inden Ã¶nce, en yakÄ±n uzaktaki alana eriÅŸmek iÃ§in ${accessPreviousSpace} basÄ±n, Ã¶rneÄŸin: iki birleÅŸik HR elementleri. AynÄ± tuÅŸ kombinasyonu tekrarÄ±yla diÄŸer alanlarada ulaÅŸÄ±n."},{name:"Sonraki komut alanÄ±na odaklan",legend:"DÃ¼zeltme imleÃ§inden sonra, en yakÄ±n uzaktaki alana eriÅŸmek iÃ§in ${accessNextSpace} basÄ±n, Ã¶rneÄŸin: iki birleÅŸik HR elementleri. AynÄ± tuÅŸ kombinasyonu tekrarÄ±yla diÄŸer alanlarada ulaÅŸÄ±n."},
{name:"EriÅŸilebilirlik YardÄ±mÄ±",legend:"${a11yHelp}'e basÄ±n"}]}],backspace:"Silme",tab:"Sekme tuÅŸu",enter:"Gir tuÅŸu",shift:'"Shift" KaydÄ±rma tuÅŸu',ctrl:'"Ctrl" Kontrol tuÅŸu',alt:'"Alt" Anahtar tuÅŸu',pause:"Durdurma tuÅŸu",capslock:"BÃ¼yÃ¼k harf tuÅŸu",escape:"VazgeÃ§ tuÅŸu",pageUp:"Sayfa YukarÄ±",pageDown:"Sayfa AÅŸaÄŸÄ±",end:"Sona",home:"En baÅŸa",leftArrow:"Sol ok",upArrow:"YukarÄ± ok",rightArrow:"SaÄŸ ok",downArrow:"AÅŸaÄŸÄ± ok",insert:"Araya gir","delete":"Silme",leftWindowKey:"Sol windows tuÅŸu",rightWindowKey:"SaÄŸ windows tuÅŸu",
selectKey:"SeÃ§me tuÅŸu",numpad0:"NÃ¼merik 0",numpad1:"NÃ¼merik 1",numpad2:"NÃ¼merik 2",numpad3:"NÃ¼merik 3",numpad4:"NÃ¼merik 4",numpad5:"NÃ¼merik 5",numpad6:"NÃ¼merik 6",numpad7:"NÃ¼merik 7",numpad8:"NÃ¼merik 8",numpad9:"NÃ¼merik 9",multiply:"Ã‡arpma",add:"Toplama",subtract:"Ã‡Ä±karma",decimalPoint:"OndalÄ±k iÅŸareti",divide:"BÃ¶lme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lk",scrollLock:"Scr Lk",semiColon:"NoktalÄ± virgÃ¼l",equalSign:"EÅŸittir",
comma:"VirgÃ¼l",dash:"Eksi",period:"Nokta",forwardSlash:"Ä°leri eÄŸik Ã§izgi",graveAccent:"Ãœst tÄ±rnak",openBracket:"Parantez aÃ§",backSlash:"Ters eÄŸik Ã§izgi",closeBracket:"Parantez kapa",singleQuote:"Tek tÄ±rnak"});
