/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"HÆ°á»›ng dáº«n trá»£ nÄƒng",contents:"Ná»™i dung Há»— trá»£. Nháº¥n ESC Ä‘á»ƒ Ä‘Ã³ng há»™p thoáº¡i.",legend:[{name:"Chung",items:[{name:"Thanh cÃ´ng cá»¥ soáº¡n tháº£o",legend:"Nháº¥n ${toolbarFocus} Ä‘á»ƒ Ä‘iá»u hÆ°á»›ng Ä‘áº¿n thanh cÃ´ng cá»¥. Nháº¥n TAB vÃ  SHIFT+TAB Ä‘á»ƒ chuyá»ƒn Ä‘áº¿n nhÃ³m thanh cÃ´ng cá»¥ khÃ¡c. Nháº¥n MÅ¨I TÃŠN PHáº¢I hoáº·c MÅ¨I TÃŠN TRÃI Ä‘á»ƒ chuyá»ƒn sang nÃºt khÃ¡c trÃªn thanh cÃ´ng cá»¥. Nháº¥n PHÃM CÃCH hoáº·c ENTER Ä‘á»ƒ kÃ­ch hoáº¡t nÃºt trÃªn thanh cÃ´ng cá»¥."},{name:"Há»™p thoáº¡i BiÃªn t",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"TrÃ¬nh Ä‘Æ¡n Ngá»¯ cáº£nh cBá»™ soáº¡n tháº£o",legend:"Nháº¥n ${contextMenu} hoáº·c PHÃM á»¨NG Dá»¤NG Ä‘á»ƒ má»Ÿ thá»±c Ä‘Æ¡n ngá»¯ cáº£nh. Sau Ä‘Ã³ nháº¥n TAB hoáº·c MÅ¨I TÃŠN XUá»NG Ä‘á»ƒ di chuyá»ƒn Ä‘áº¿n tuá»³ chá»n tiáº¿p theo cá»§a thá»±c Ä‘Æ¡n. Nháº¥n SHIFT+TAB hoáº·c MÅ¨I TÃŠN LÃŠN Ä‘á»ƒ quay láº¡i tuá»³ chá»n trÆ°á»›c. Nháº¥n Dáº¤U CÃCH hoáº·c ENTER Ä‘á»ƒ chá»n tuá»³ chá»n cá»§a thá»±c Ä‘Æ¡n. Nháº¥n Dáº¤U CÃCH hoáº·c ENTER hoáº·c MÅ¨I TÃŠN SANG PHáº¢I Ä‘á»ƒ má»Ÿ thá»±c Ä‘Æ¡n con cá»§a tuá»³ chá»n hiá»‡n táº¡i. Nháº¥n ESC hoáº·c MÅ¨I TÃŠN SANG TRÃI Ä‘á»ƒ quay trá»Ÿ láº¡i thá»±c Ä‘Æ¡n gá»‘c. Nháº¥n ESC Ä‘á»ƒ Ä‘Ã³ng thá»±c Ä‘Æ¡n ngá»¯ cáº£nh."},
{name:"Há»™p danh sÃ¡ch trÃ¬nh biÃªn táº­p",legend:"Trong má»™t danh sÃ¡ch chá»n, di chuyá»ƒn Ä‘á»‘i tÆ°á»£ng tiáº¿p theo vá»›i phÃ­m TAB hoáº·c phÃ­m mÅ©i tÃªn hÆ°á»›ng xuá»‘ng. Di chuyá»ƒn Ä‘áº¿n Ä‘á»‘i tÆ°á»£ng trÆ°á»›c Ä‘Ã³ báº±ng cÃ¡ch nháº¥n tá»• há»£p phÃ­m SHIFT+TAB hoáº·c mÅ©i tÃªn hÆ°á»›ng lÃªn. PhÃ­m khoáº£ng cÃ¡ch hoáº·c phÃ­m ENTER Ä‘á»ƒ chá»n cÃ¡c tÃ¹y chá»n trong danh sÃ¡ch. Nháº¥n phÃ­m ESC Ä‘á»ƒ Ä‘Ã³ng láº¡i danh sÃ¡ch chá»n."},{name:"Thanh Ä‘Æ°á»ng dáº«n cÃ¡c Ä‘á»‘i tÆ°á»£ng",legend:"Nháº¥n ${elementsPathFocus} Ä‘á»ƒ Ä‘iá»u hÆ°á»›ng cÃ¡c Ä‘á»‘i tÆ°á»£ng trong thanh Ä‘Æ°á»ng dáº«n. Di chuyá»ƒn Ä‘áº¿n Ä‘á»‘i tÆ°á»£ng tiáº¿p theo báº±ng phÃ­m TAB hoáº·c phÃ­m mÅ©i tÃªn bÃªn pháº£i. Di chuyá»ƒn Ä‘áº¿n Ä‘á»‘i tÆ°á»£ng trÆ°á»›c Ä‘Ã³ báº±ng tá»• há»£p phÃ­m SHIFT+TAB hoáº·c phÃ­m mÅ©i tÃªn bÃªn trÃ¡i. Nháº¥n phÃ­m khoáº£ng cÃ¡ch hoáº·c ENTER Ä‘á»ƒ chá»n Ä‘á»‘i tÆ°á»£ng trong trÃ¬nh soáº¡n tháº£o."}]},
{name:"Lá»‡nh",items:[{name:"LÃ m láº¡i lá»‡n",legend:"áº¤n ${undo}"},{name:"LÃ m láº¡i lá»‡nh",legend:"áº¤n ${redo}"},{name:"Lá»‡nh in Ä‘áº­m",legend:"áº¤n ${bold}"},{name:"Lá»‡nh in nghiÃªng",legend:"áº¤n ${italic}"},{name:"Lá»‡nh gáº¡ch dÆ°á»›i",legend:"áº¤n ${underline}"},{name:"Lá»‡nh liÃªn káº¿t",legend:"Nháº¥n ${link}"},{name:"Lá»‡nh hiá»ƒn thá»‹ thanh cÃ´ng cá»¥",legend:"Nháº¥n${toolbarCollapse}"},{name:"Truy cáº­p Ä‘áº¿n lá»‡nh táº­p trung vÃ o khoáº£ng cÃ¡ch trÆ°á»›c Ä‘Ã³",legend:"áº¤n ${accessPreviousSpace} Ä‘á»ƒ truy cáº­p Ä‘áº¿n pháº§n táº­p trung khoáº£ng cÃ¡ch sau pháº§n cÃ²n sÃ³t láº¡i cá»§a khoáº£ng cÃ¡ch gáº§n nháº¥t vá»‘n khÃ´ng tÃ¡c Ä‘á»™ng Ä‘áº¿n Ä‘Æ°á»£c , thÃ­ dá»¥: hai yáº¿u tá»‘ Ä‘iá»u chá»‰nh HR. Láº·p láº¡i cÃ¡c phÃ­m káº¿t há»ep nÃ y Ä‘á»ƒ vÆ°Æ¡n Ä‘áº¿n pháº§n khoáº£ng cÃ¡ch."},
{name:"Truy cáº­p pháº§n Ä‘á»‘i tÆ°á»£ng lá»‡nh khoáº£ng trá»‘ng",legend:"áº¤n ${accessNextSpace} Ä‘á»ƒ truy cáº­p Ä‘áº¿n pháº§n táº­p trung khoáº£ng cÃ¡ch sau pháº§n cÃ²n sÃ³t láº¡i cá»§a khoáº£ng cÃ¡ch gáº§n nháº¥t vá»‘n khÃ´ng tÃ¡c Ä‘á»™ng Ä‘áº¿n Ä‘Æ°á»£c , thÃ­ dá»¥: hai yáº¿u tá»‘ Ä‘iá»u chá»‰nh HR. Láº·p láº¡i cÃ¡c phÃ­m káº¿t há»ep nÃ y Ä‘á»ƒ vÆ°Æ¡n Ä‘áº¿n pháº§n khoáº£ng cÃ¡ch."},{name:"Trá»£ giÃºp liÃªn quan",legend:"Nháº¥n ${a11yHelp}"}]}],backspace:"PhÃ­m Backspace",tab:"PhÃ­m Tab",enter:"PhÃ­m Tab",shift:"PhÃ­m Shift",ctrl:"PhÃ­m Ctrl",alt:"PhÃ­m Alt",pause:"PhÃ­m Pause",capslock:"PhÃ­m Caps Lock",
escape:"PhÃ­m Escape",pageUp:"PhÃ­m Page Up",pageDown:"PhÃ­m Page Down",end:"PhÃ­m End",home:"PhÃ­m Home",leftArrow:"PhÃ­m Left Arrow",upArrow:"PhÃ­m Up Arrow",rightArrow:"PhÃ­m Right Arrow",downArrow:"PhÃ­m Down Arrow",insert:"ChÃ¨n","delete":"XÃ³a",leftWindowKey:"PhÃ­m Left Windows",rightWindowKey:"PhÃ­m Right Windows ",selectKey:"Chá»n phÃ­m",numpad0:"PhÃ­m 0",numpad1:"PhÃ­m 1",numpad2:"PhÃ­m 2",numpad3:"PhÃ­m 3",numpad4:"PhÃ­m 4",numpad5:"PhÃ­m 5",numpad6:"PhÃ­m 6",numpad7:"PhÃ­m 7",numpad8:"PhÃ­m 8",numpad9:"PhÃ­m 9",
multiply:"NhÃ¢n",add:"ThÃªm",subtract:"Trá»«",decimalPoint:"Äiá»ƒm sá»‘ tháº­p phÃ¢n",divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Dáº¥u cháº¥m pháº©y",equalSign:"ÄÄƒng nháº­p báº±ng",comma:"Dáº¥u pháº©y",dash:"Dáº¥u gáº¡ch ngang",period:"PhÃ­m .",forwardSlash:"PhÃ­m /",graveAccent:"PhÃ­m `",openBracket:"Open Bracket",backSlash:"Dáº¥u gáº¡ch chÃ©o ngÆ°á»£c",closeBracket:"Gáº§n giÃ¡ Ä‘á»¡",singleQuote:"TrÃ­ch dáº«n"});
