/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","he",{euro:"×™×•×¨×•",lsquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×™×—×™×“ ×©×ž××œ×™",rsquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×™×—×™×“ ×™×ž× ×™",ldquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×›×¤×•×œ ×©×ž××œ×™",rdquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×›×¤×•×œ ×™×ž× ×™",ndash:"×§×• ×ž×¤×¨×™×“ ×§×¦×¨",mdash:"×§×• ×ž×¤×¨×™×“ ××¨×•×š",iexcl:"×¡×™×ž×Ÿ ×§×¨×™××” ×”×¤×•×š",cent:"×¡× ×˜",pound:"×¤××•× ×“",curren:"×ž×˜×‘×¢",yen:"×™×Ÿ",brvbar:"×§×• ×©×‘×•×¨",sect:"×¡×™×ž×Ÿ ×ž×§×˜×¢",uml:"×©×ª×™ × ×§×•×“×•×ª ××•×¤×§×™×•×ª (Diaeresis)",copy:"×¡×™×ž×Ÿ ×–×›×•×™×•×ª ×™×•×¦×¨×™× (Copyright)",ordf:"×¡×™×ž×Ÿ ××•×¨×“×™× ××œ×™ × ×§×‘×™",laquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×–×•×•×™×ª ×›×¤×•×œ×” ×œ×©×ž××œ",not:"×¡×™×ž×Ÿ ×©×œ×™×œ×” ×ž×ª×ž×˜×™",reg:"×¡×™×ž×Ÿ ×¨×©×•×",
macr:"×ž×§×¨×•×Ÿ (×”×’×™×” ××¨×•×›×”)",deg:"×ž×¢×œ×•×ª",sup2:"2 ×‘×›×ª×™×‘ ×¢×™×œ×™",sup3:"3 ×‘×›×ª×™×‘ ×¢×™×œ×™",acute:"×¡×™×ž×Ÿ ×“×’×•×© (Acute)",micro:"×ž×™×§×¨×•",para:"×¡×™×ž×•×Ÿ ×¤×¡×§×”",middot:"× ×§×•×“×” ××ž×¦×¢×™×ª",cedil:"×¡×“×™×œ×™×”",sup1:"1 ×‘×›×ª×™×‘ ×¢×™×œ×™",ordm:"×¡×™×ž×Ÿ ××•×¨×“×™× ××œ×™ ×–×›×¨×™",raquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ ×–×•×•×™×ª ×›×¤×•×œ×” ×œ×™×ž×™×Ÿ",frac14:"×¨×‘×¢ ×‘×©×‘×¨ ×¤×©×•×˜",frac12:"×—×¦×™ ×‘×©×‘×¨ ×¤×©×•×˜",frac34:"×©×œ×•×©×” ×¨×‘×¢×™× ×‘×©×‘×¨ ×¤×©×•×˜",iquest:"×¡×™×ž×Ÿ ×©××œ×” ×”×¤×•×š",Agrave:"××•×ª ×œ×˜×™× ×™×ª A ×¢× ×’×¨×© (Grave)",Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",
Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"××•×ª ×œ×˜×™× ×™×ª Ã† ×’×“×•×œ×”",Ccedil:"Latin capital letter C with cedilla",Egrave:"××•×ª ×œ×˜×™× ×™×ª E ×¢× ×’×¨×© (Grave)",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"××•×ª ×œ×˜×™× ×™×ª I ×¢× ×’×¨×© (Grave)",Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",
ETH:"××•×ª ×œ×˜×™× ×™×ª Eth ×’×“×•×œ×”",Ntilde:"Latin capital letter N with tilde",Ograve:"××•×ª ×œ×˜×™× ×™×ª O ×¢× ×’×¨×© (Grave)",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"×¡×™×ž×Ÿ ×›×¤×œ",Oslash:"Latin capital letter O with stroke",Ugrave:"××•×ª ×œ×˜×™× ×™×ª U ×¢× ×’×¨×© (Grave)",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",
Yacute:"Latin capital letter Y with acute accent",THORN:"××•×ª ×œ×˜×™× ×™×ª Thorn ×’×“×•×œ×”",szlig:"××•×ª ×œ×˜×™× ×™×ª s ×—×“×” ×§×˜× ×”",agrave:"××•×ª ×œ×˜×™× ×™×ª a ×¢× ×’×¨×© (Grave)",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"××•×ª ×œ×˜×™× ×™×ª Ã¦ ×§×˜× ×”",ccedil:"Latin small letter c with cedilla",egrave:"××•×ª ×œ×˜×™× ×™×ª e ×¢× ×’×¨×© (Grave)",eacute:"Latin small letter e with acute accent",
ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"××•×ª ×œ×˜×™× ×™×ª i ×¢× ×’×¨×© (Grave)",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"××•×ª ×œ×˜×™× ×™×ª eth ×§×˜× ×”",ntilde:"Latin small letter n with tilde",ograve:"××•×ª ×œ×˜×™× ×™×ª o ×¢× ×’×¨×© (Grave)",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",
divide:"×¡×™×ž×Ÿ ×—×œ×•×§×”",oslash:"Latin small letter o with stroke",ugrave:"××•×ª ×œ×˜×™× ×™×ª u ×¢× ×’×¨×© (Grave)",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"××•×ª ×œ×˜×™× ×™×ª thorn ×§×˜× ×”",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",
373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ × ×ž×•×š ×™×—×™×“",8219:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜",bdquo:"×¡×™×ž×Ÿ ×¦×™×˜×•×˜ × ×ž×•×š ×›×¤×•×œ",hellip:"×©×œ×•×© × ×§×•×“×•×ª",trade:"×¡×™×ž×Ÿ ×˜×¨×™×™×“×ž××¨×§",9658:"×¡×ž×Ÿ ×©×—×•×¨ ×œ×¦×“ ×™×ž×™×Ÿ",bull:"×ª×‘×œ×™×˜ (×¨×©×™×ž×”)",rarr:"×—×¥ ×œ×™×ž×™×Ÿ",rArr:"×—×¥ ×›×¤×•×œ ×œ×™×ž×™×Ÿ",hArr:"×—×¥ ×›×¤×•×œ ×œ×™×ž×™×Ÿ ×•×©×ž××œ",diams:"×™×”×œ×•× ×ž×œ×",asymp:"×›×ž×¢×˜ ×©×•×•×”"});
