/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zÄ«me",lsquo:"KreisÄ  vienkÄrtÄ«ga pÄ“diÅ†a",rsquo:"LabÄ  vienkÄrtÄ«ga pÄ“diÅ†a",ldquo:"KreisÄ  dubult pÄ“diÅ†a",rdquo:"LabÄ dubult pÄ“diÅ†a",ndash:"En svÄ«tra",mdash:"Em svÄ«tra",iexcl:"Apgriezta izsaukuma zÄ«me",cent:"Centu naudas zÄ«me",pound:"SterliÅ†u mÄrciÅ†u naudas zÄ«me",curren:"ValÅ«tas zÄ«me",yen:"Jenu naudas zÄ«me",brvbar:"VertikÄla pÄrrauta lÄ«nija",sect:"ParagrÄfa zÄ«me",uml:"Diakritiska zÄ«me",copy:"AutortiesÄ«bu zÄ«me",ordf:"SieviÅ¡Ä·as kÄrtas rÄdÄ«tÄjs",
laquo:"KreisÄ dubult stÅ«ra pÄ“diÅ†u zÄ«me",not:"NeparakstÄ«ts",reg:"ReÄ£istrÄ“ta zÄ«me",macr:"GarumzÄ«me",deg:"GrÄdu zÄ«me",sup2:"AugÅ¡raksts divi",sup3:"AugÅ¡raksts trÄ«s",acute:"AkÅ«ta uzsvara zÄ«me",micro:"Mikro zÄ«me",para:"Rindkopas zÄ«me ",middot:"VidÄ“js punkts",cedil:"Ä€Ä·Ä«tis zem burta",sup1:"AugÅ¡raksts viens",ordm:"VÄ«riÅ¡Ä·Ä«gas kÄrtas rÄdÄ«tÄjs",raquo:"LabÄ dubult stÅ«ra pÄ“diÅ†u zÄ«me",frac14:"VulgÄra frakcija 1/4",frac12:"VulgÄra frakcija 1/2",frac34:"VulgÄra frakcija 3/4",iquest:"Apgriezta jautÄjuma zÄ«me",Agrave:"Lielais latÄ«Å†u burts A ar uzsvara zÄ«mi",
Aacute:"Lielais  latÄ«Å†u burts A ar akÅ«tu uzsvara zÄ«mi",Acirc:"Lielais latÄ«Å†u burts A ar diakritisku zÄ«mi",Atilde:"Lielais latÄ«Å†u burts A ar tildi ",Auml:"Lielais latÄ«Å†u burts A ar diakritisko zÄ«mi",Aring:"Lielais latÄ«Å†u burts A ar aplÄ«ti augÅ¡Ä",AElig:"Lielais latÄ«Å†u burts Ã†",Ccedil:"Lielais latÄ«Å†u burts C ar ÄÄ·Ä«ti zem burta",Egrave:"Lielais latÄ«Å†u burts E ar apostrofu",Eacute:"Lielais latÄ«Å†u burts E ar akÅ«tu uzsvara zÄ«mi",Ecirc:"Lielais latÄ«Å†u burts E ar diakritisko zÄ«mi",Euml:"Lielais latÄ«Å†u burts E ar diakritisko zÄ«mi",
Igrave:"Lielais latÄ«Å†u burts I ar uzsvaras  zÄ«mi",Iacute:"Lielais latÄ«Å†u burts I ar akÅ«tu uzsvara zÄ«mi",Icirc:"Lielais latÄ«Å†u burts I ar diakritisko zÄ«mi",Iuml:"Lielais latÄ«Å†u burts I ar diakritisko zÄ«mi",ETH:"Lielais latÄ«Å†u burts Eth",Ntilde:"Lielais latÄ«Å†u burts N ar tildi",Ograve:"Lielais latÄ«Å†u burts O ar uzsvara zÄ«mi",Oacute:"Lielais latÄ«Å†u burts O ar akÅ«to uzsvara zÄ«mi",Ocirc:"Lielais latÄ«Å†u burts O ar diakritisko zÄ«mi",Otilde:"Lielais latÄ«Å†u burts O ar tildi",Ouml:"Lielais latÄ«Å†u burts O ar diakritisko zÄ«mi",
times:"ReizinÄÅ¡anas zÄ«me ",Oslash:"Lielais latÄ«Å†u burts O ar iesvÄ«trojumu",Ugrave:"Lielais latÄ«Å†u burts U ar uzsvaras zÄ«mi",Uacute:"Lielais latÄ«Å†u burts U ar akÅ«to uzsvars zÄ«mi",Ucirc:"Lielais latÄ«Å†u burts U ar diakritisko zÄ«mi",Uuml:"Lielais latÄ«Å†u burts U ar diakritisko zÄ«mi",Yacute:"Lielais latÄ«Å†u burts Y ar akÅ«to uzsvaras zÄ«mi",THORN:"Lielais latÄ«Å†u burts torn",szlig:"Mazs latÄ«Å†u burts ar ligatÅ«ru",agrave:"Mazs latÄ«Å†u burts a ar uzsvara zÄ«mi",aacute:"Mazs latÄ«Å†u burts a ar akÅ«to uzsvara zÄ«mi",
acirc:"Mazs latÄ«Å†u burts a ar diakritisko zÄ«mi",atilde:"Mazs latÄ«Å†u burts a ar tildi",auml:"Mazs latÄ«Å†u burts a ar diakritisko zÄ«mi",aring:"Mazs latÄ«Å†u burts a ar aplÄ«ti augÅ¡Ä",aelig:"Mazs latÄ«Å†u burts Ã¦",ccedil:"Mazs latÄ«Å†u burts c ar ÄÄ·Ä«ti zem burta",egrave:"Mazs latÄ«Å†u burts e ar uzsvara zÄ«mi ",eacute:"Mazs latÄ«Å†u burts e ar akÅ«tu uzsvara zÄ«mi",ecirc:"Mazs latÄ«Å†u burts e ar diakritisko zÄ«mi",euml:"Mazs latÄ«Å†u burts e ar diakritisko zÄ«mi",igrave:"Mazs latÄ«Å†u burts i ar uzsvara zÄ«mi ",iacute:"Mazs latÄ«Å†u burts i ar akÅ«tu uzsvara zÄ«mi",
icirc:"Mazs latÄ«Å†u burts i ar diakritisko zÄ«mi",iuml:"Mazs latÄ«Å†u burts i ar diakritisko zÄ«mi",eth:"Mazs latÄ«Å†u burts eth",ntilde:"Mazs latÄ«Å†u burts n ar tildi",ograve:"Mazs latÄ«Å†u burts o ar uzsvara zÄ«mi ",oacute:"Mazs latÄ«Å†u burts o ar akÅ«tu uzsvara zÄ«mi",ocirc:"Mazs latÄ«Å†u burts o ar diakritisko zÄ«mi",otilde:"Mazs latÄ«Å†u burts o ar tildi",ouml:"Mazs latÄ«Å†u burts o ar diakritisko zÄ«mi",divide:"DalÄ«Å¡anas zÄ«me",oslash:"Mazs latÄ«Å†u burts o ar iesvÄ«trojumu",ugrave:"Mazs latÄ«Å†u burts u ar uzsvara zÄ«mi ",
uacute:"Mazs latÄ«Å†u burts u ar  akÅ«tu uzsvara zÄ«mi",ucirc:"Mazs latÄ«Å†u burts u ar diakritisko zÄ«mi",uuml:"Mazs latÄ«Å†u burts u ar diakritisko zÄ«mi",yacute:"Mazs latÄ«Å†u burts y ar  akÅ«tu uzsvaras zÄ«mi",thorn:"Mazs latÄ«Å†u burts torns",yuml:"Mazs latÄ«Å†u burts y ar diakritisko zÄ«mi",OElig:"Liela latÄ«Å†u ligatÅ«ra OE",oelig:"Maza latÄ«Å†u ligatÅ«ra oe",372:"Liels latÄ«Å†u burts W ar diakritisko zÄ«mi ",374:"Liels latÄ«Å†u burts Y ar diakritisko zÄ«mi ",373:"Mazs latÄ«Å†u burts w ar diakritisko zÄ«mi ",375:"Mazs latÄ«Å†u burts y ar diakritisko zÄ«mi ",
sbquo:"Mazas-9 vienkÄrtÄ«gas pÄ“diÅ†as",8219:"Lielas-9 vienkÄrtÄ«gas apgrieztas pÄ“diÅ†as",bdquo:"Mazas-9 dubultas pÄ“diÅ†as",hellip:"HorizontÄli daudzpunkti",trade:"PreÄu zÄ«mes zÄ«me",9658:"Melns pa labi pagriezts radÄ«tÄjs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"GandrÄ«z vienÄds ar"});
