/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","nb",{euro:"Eurosymbol",lsquo:"Venstre enkelt anfÃ¸rselstegn",rsquo:"HÃ¸yre enkelt anfÃ¸rselstegn",ldquo:"Venstre dobbelt anfÃ¸rselstegn",rdquo:"HÃ¸yre anfÃ¸rsesltegn",ndash:"Kort tankestrek",mdash:"Lang tankestrek",iexcl:"Omvendt utropstegn",cent:"Centsymbol",pound:"Pundsymbol",curren:"Valutategn",yen:"Yensymbol",brvbar:"Brutt loddrett strek",sect:"Paragraftegn",uml:"TÃ¸ddel",copy:"Copyrighttegn",ordf:"Feminin ordensindikator",laquo:"Venstre anfÃ¸rselstegn",not:"Negasjonstegn",
reg:"Registrert varemerke-tegn",macr:"Makron",deg:"Gradsymbol",sup2:"Hevet totall",sup3:"Hevet tretall",acute:"Akutt aksent",micro:"Mikrosymbol",para:"Avsnittstegn",middot:"Midtstilt prikk",cedil:"Cedille",sup1:"Hevet ettall",ordm:"Maskulin ordensindikator",raquo:"HÃ¸yre anfÃ¸rselstegn",frac14:"FjerdedelsbrÃ¸k",frac12:"HalvbrÃ¸k",frac34:"Tre fjerdedelers brÃ¸k",iquest:"Omvendt spÃ¸rsmÃ¥lstegn",Agrave:"Stor A med grav aksent",Aacute:"Stor A med akutt aksent",Acirc:"Stor A med cirkumfleks",Atilde:"Stor A med tilde",
Auml:"Stor A med tÃ¸ddel",Aring:"Stor Ã…",AElig:"Stor Ã†",Ccedil:"Stor C med cedille",Egrave:"Stor E med grav aksent",Eacute:"Stor E med akutt aksent",Ecirc:"Stor E med cirkumfleks",Euml:"Stor E med tÃ¸ddel",Igrave:"Stor I med grav aksent",Iacute:"Stor I med akutt aksent",Icirc:"Stor I med cirkumfleks",Iuml:"Stor I med tÃ¸ddel",ETH:"Stor Edd/stungen D",Ntilde:"Stor N med tilde",Ograve:"Stor O med grav aksent",Oacute:"Stor O med akutt aksent",Ocirc:"Stor O med cirkumfleks",Otilde:"Stor O med tilde",Ouml:"Stor O med tÃ¸ddel",
times:"Multiplikasjonstegn",Oslash:"Stor Ã˜",Ugrave:"Stor U med grav aksent",Uacute:"Stor U med akutt aksent",Ucirc:"Stor U med cirkumfleks",Uuml:"Stor U med tÃ¸ddel",Yacute:"Stor Y med akutt aksent",THORN:"Stor Thorn",szlig:"Liten dobbelt-s/Eszett",agrave:"Liten a med grav aksent",aacute:"Liten a med akutt aksent",acirc:"Liten a med cirkumfleks",atilde:"Liten a med tilde",auml:"Liten a med tÃ¸ddel",aring:"Liten Ã¥",aelig:"Liten Ã¦",ccedil:"Liten c med cedille",egrave:"Liten e med grav aksent",eacute:"Liten e med akutt aksent",
ecirc:"Liten e med cirkumfleks",euml:"Liten e med tÃ¸ddel",igrave:"Liten i med grav aksent",iacute:"Liten i med akutt aksent",icirc:"Liten i med cirkumfleks",iuml:"Liten i med tÃ¸ddel",eth:"Liten edd/stungen d",ntilde:"Liten n med tilde",ograve:"Liten o med grav aksent",oacute:"Liten o med akutt aksent",ocirc:"Liten o med cirkumfleks",otilde:"Liten o med tilde",ouml:"Liten o med tÃ¸ddel",divide:"Divisjonstegn",oslash:"Liten Ã¸",ugrave:"Liten u med grav aksent",uacute:"Liten u med akutt aksent",ucirc:"Liten u med cirkumfleks",
uuml:"Liten u med tÃ¸ddel",yacute:"Liten y med akutt aksent",thorn:"Liten thorn",yuml:"Liten y med tÃ¸ddel",OElig:"Stor ligatur av O og E",oelig:"Liten ligatur av o og e",372:"Stor W med cirkumfleks",374:"Stor Y med cirkumfleks",373:"Liten w med cirkumfleks",375:"Liten y med cirkumfleks",sbquo:"Enkelt lavt 9-anfÃ¸rselstegn",8219:"Enkelt hÃ¸yt reversert 9-anfÃ¸rselstegn",bdquo:"Dobbelt lavt 9-anfÃ¸rselstegn",hellip:"Ellipse",trade:"Varemerkesymbol",9658:"Svart hÃ¸yrevendt peker",bull:"Tykk interpunkt",rarr:"HÃ¸yrevendt pil",
rArr:"Dobbel hÃ¸yrevendt pil",hArr:"Dobbel venstrevendt pil",diams:"Svart ruter",asymp:"Omtrent likhetstegn"});
