/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Znak za evro",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"PomiÅ¡ljaj",mdash:"Dolgi pomiÅ¡ljaj",iexcl:"Obrnjen klicaj",cent:"Znak za cent",pound:"Znak za funt",curren:"Znak valute",yen:"Znak za jen",brvbar:"Zlomljena Ärta",sect:"Znak za Älen",uml:"Diereza",copy:"Znak avtorskih pravic",ordf:"Å½enski zaporedni kazalnik",laquo:"Levi dvojni lomljeni narekovaj",not:"Znak za ne",
reg:"Registrirani znak",macr:"NadÄrtano",deg:"Znak za stopinje",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Znak za mikro",para:"Znak za odstavek",middot:"Usredinjena pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"MoÅ¡ki zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena Äetrtina",frac12:"Ena polovica",frac34:"Tri Äetrtine",iquest:"Obrnjen vpraÅ¡aj",Agrave:"Velika latinska Ärka A s krativcem",Aacute:"Velika latinska Ärka A z ostrivcem",Acirc:"Velika latinska Ärka A s streÅ¡ico",
Atilde:"Velika latinska Ärka A z tildo",Auml:"Velika latinska Ärka A z diaeresis-om",Aring:"Velika latinska Ärka A z obroÄem",AElig:"Velika latinska Ärka Ã†",Ccedil:"Velika latinska Ärka C s cedillo",Egrave:"Velika latinska Ärka E s krativcem",Eacute:"Velika latinska Ärka E z ostrivcem",Ecirc:"Velika latinska Ärka E s streÅ¡ico",Euml:"Velika latinska Ärka E z diaeresis-om",Igrave:"Velika latinska Ärka I s krativcem",Iacute:"Velika latinska Ärka I z ostrivcem",Icirc:"Velika latinska Ärka I s streÅ¡ico",
Iuml:"Velika latinska Ärka I z diaeresis-om",ETH:"Velika latinska Ärka Eth",Ntilde:"Velika latinska Ärka N s tildo",Ograve:"Velika latinska Ärka O s krativcem",Oacute:"Velika latinska Ärka O z ostrivcem",Ocirc:"Velika latinska Ärka O s streÅ¡ico",Otilde:"Velika latinska Ärka O s tildo",Ouml:"Velika latinska Ärka O z diaeresis-om",times:"Znak za mnoÅ¾enje",Oslash:"Velika preÄrtana latinska Ärka O",Ugrave:"Velika latinska Ärka U s krativcem",Uacute:"Velika latinska Ärka U z ostrivcem",Ucirc:"Velika latinska Ärka U s streÅ¡ico",
Uuml:"Velika latinska Ärka U z diaeresis-om",Yacute:"Velika latinska Ärka Y z ostrivcem",THORN:"Velika latinska Ärka Thorn",szlig:"Mala ostra latinska Ärka s",agrave:"Mala latinska Ärka a s krativcem",aacute:"Mala latinska Ärka a z ostrivcem",acirc:"Mala latinska Ärka a s streÅ¡ico",atilde:"Mala latinska Ärka a s tildo",auml:"Mala latinska Ärka a z diaeresis-om",aring:"Mala latinska Ärka a z obroÄem",aelig:"Mala latinska Ärka Ã¦",ccedil:"Mala latinska Ärka c s cedillo",egrave:"Mala latinska Ärka e s krativcem",
eacute:"Mala latinska Ärka e z ostrivcem",ecirc:"Mala latinska Ärka e s streÅ¡ico",euml:"Mala latinska Ärka e z diaeresis-om",igrave:"Mala latinska Ärka i s krativcem",iacute:"Mala latinska Ärka i z ostrivcem",icirc:"Mala latinska Ärka i s streÅ¡ico",iuml:"Mala latinska Ärka i z diaeresis-om",eth:"Mala latinska Ärka eth",ntilde:"Mala latinska Ärka n s tildo",ograve:"Mala latinska Ärka o s krativcem",oacute:"Mala latinska Ärka o z ostrivcem",ocirc:"Mala latinska Ärka o s streÅ¡ico",otilde:"Mala latinska Ärka o s tildo",
ouml:"Mala latinska Ärka o z diaeresis-om",divide:"Znak za deljenje",oslash:"Mala preÄrtana latinska Ärka o",ugrave:"Mala latinska Ärka u s krativcem",uacute:"Mala latinska Ärka u z ostrivcem",ucirc:"Mala latinska Ärka u s streÅ¡ico",uuml:"Mala latinska Ärka u z diaeresis-om",yacute:"Mala latinska Ärka y z ostrivcem",thorn:"Mala latinska Ärka thorn",yuml:"Mala latinska Ärka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska Ärka W s streÅ¡ico",
374:"Velika latinska Ärka Y s streÅ¡ico",373:"Mala latinska Ärka w s streÅ¡ico",375:"Mala latinska Ärka y s streÅ¡ico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"ÄŒrni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena puÅ¡Äica",rArr:"Desno-usmerjena dvojna puÅ¡Äica",hArr:"Leva in desna dvojna puÅ¡Äica",diams:"ÄŒrna kara",asymp:"Skoraj enako"});
